// Letras sincronizadas de las canciones
const lyrics = {
    "Marry You": [
  { time: 12.86, text: "Es una noche hermosa" },
  { time: 15.35, text: "Estamos buscando hacer alguna locura" },
  { time: 18.96, text: "Hey, amor" },
  { time: 21.39, text: "Creo que quiero casarme contigo" },
  { time: 25.74, text: "¿Es la mirada en tus ojos?" },
  { time: 28.17, text: "¿O es este jugo que baila?" },
  { time: 32.58, text: "¿A quién le importa, amor?" },
  { time: 34.20, text: "Creo que quiero casarme contigo" },
  { time: 39.36, text: "Conozco una pequeña capilla en el boulevard a la que podemos ir" },
  { time: 45.21, text: "Nadie lo sabrá" },
  { time: 48.77, text: "Vamos, nena" },
  { time: 52.43, text: "¿A quién le importa si estamos locos? Tengo un bolsillo lleno de dinero para gastar" },
  { time: 58.53, text: "Shots de Patrón" },
  { time: 61.50, text: "Y empieza todo, nena" },
  { time: 65.49, text: "No digas no, no, no, no-no" },
  { time: 68.48, text: "Solo di sí, sí, sí, sí-sí" },
  { time: 72.15, text: "Y nos iremos, iremos, iremos, iremos" },
  { time: 75.19, text: "Si estás lista, como yo lo estoy" },
  { time: 78.68, text: "Es una noche hermosa" },
  { time: 81.23, text: "Estamos buscando hacer alguna locura" },
  { time: 84.95, text: "Hey, amor" },
  { time: 86.45, text: "Creo que quiero casarme contigo" },
  { time: 91.93, text: "¿Es la mirada en tus ojos?" },
  { time: 94.54, text: "¿O es este jugo que baila?" },
  { time: 98.15, text: "¿A quién le importa, amor?" },
  { time: 99.96, text: "Creo que quiero casarme contigo" },
  { time: 104.81, text: "Voy a buscar un anillo, que suenen las campanas del coro como oooh" },
  { time: 110.91, text: "Entonces, ¿qué quieres hacer?" },
  { time: 114.88, text: "Vamos a escapar, nena" },
  { time: 119.19, text: "Si despertamos y quieres romper, está bien" },
  { time: 124.03, text: "No, no te culparé" },
  { time: 127.38, text: "Fue divertido, nena" },
  { time: 131.44, text: "No digas no, no, no, no-no" },
  { time: 134.42, text: "Solo di sí, sí, sí, sí-sí" },
  { time: 138.02, text: "Y nos iremos, iremos, iremos, iremos" },
  { time: 141.11, text: "Si estás lista, como yo lo estoy" },
  { time: 144.44, text: "Es una noche hermosa" },
  { time: 147.73, text: "Estamos buscando hacer alguna locura" },
  { time: 150.91, text: "Hey, amor" },
  { time: 153.14, text: "Creo que quiero casarme contigo" },
  { time: 157.56, text: "¿Es la mirada en tus ojos?" },
  { time: 160.55, text: "¿O es este jugo que baila?" },
  { time: 164.02, text: "¿A quién le importa, amor?" },
  { time: 166.40, text: "Creo que quiero casarme contigo" },
  { time: 170.25, text: "Solo di acepto" },
  { time: 177.22, text: "Dímelo ahora mismo, amor" },
  { time: 181.05, text: "Dímelo ahora mismo, amor, amor" },
  { time: 184.78, text: "Solo di acepto" },
  { time: 191.12, text: "Dímelo ahora mismo, amor" },
  { time: 194.30, text: "Dímelo ahora mismo, amor, amor" },
  { time: 198.98, text: "Es una noche hermosa" },
  { time: 200.77, text: "Estamos buscando hacer alguna locura" },
  { time: 204.32, text: "Hey, amor" },
  { time: 206.63, text: "Creo que quiero casarme contigo" },
  { time: 211.42, text: "¿Es la mirada en tus ojos?" },
  { time: 213.84, text: "¿O es este jugo que baila?" },
  { time: 217.82, text: "¿A quién le importa, amor?" },
  { time: 219.62, text: "Creo que quiero casarme contigo" }
]




,
    "Apokaluz": [
        
    ],
    "fell in luv": [
        { time: 5.01, text: "Me enamoré, me enamoré" },
        { time: 8.19, text: "Pero está bien, porque estamos enamorados" },
        { time: 11.05, text: "Oh Dios mío, me enamoré" },
        { time: 13.92, text: "Me enamoré del amor" },
        { time: 16.82, text: "Muéstrame amor, yo te doy amor" },
        { time: 19.64, text: "Me enamoré, me enamoré" },
        { time: 22.88, text: "Quiero entrar, por el amor" },
        { time: 25.64, text: "Solo muéstrame amor, solo muéstrame amor" },
        { time: 28.68, text: "Me enamoré, me enamoré" },
        { time: 31.54, text: "Y está bien, porque estoy enamorado" },
        { time: 34.24, text: "Estamos en esa cama, dame placer" },
        { time: 37.39, text: "Quiero que eso se quede" },
        { time: 40.49, text: "Cierra los ojos" },
        { time: 41.95, text: "No derrames una lágrima" },
        { time: 43.44, text: "Manténlo oscuro, cierra las cortinas" },
        { time: 46.11, text: "Estoy fuera de las pastillas, tú con ese 'lean'" },
        { time: 49.13, text: "Me haces el amor" },
        { time: 50.76, text: "Chica, haz lo tuyo" },
        { time: 52.25, text: "Tomemos algunas fotos" },
        { time: 53.75, text: "Tomemos algunas escenas, huh" },
        { time: 55.20, text: "Playboy, huh, revista, huh" },
        { time: 58.16, text: "Ella se quita la ropa interior sin T, huh" },
        { time: 61.00, text: "Ella saca sus tetas, quiere tentarme, huh" },
        { time: 63.99, text: "Ahora está tatuada, veo que lo ves, huh" },
        { time: 66.87, text: "Sé que lo ves, sé que lo ves, yo lo veo" },
        { time: 69.88, text: "Sabes que quiero a esa chica" },
        { time: 71.47, text: "Quiero comer, como" },
        { time: 72.92, text: "Quiero lamerlo" },
        { time: 74.32, text: "Quiero comer" },
        { time: 75.87, text: "Quiero congelarte" },
        { time: 77.36, text: "Quiero que esos diamantes brillen" },
        { time: 78.84, text: "Lo quiero todo sobre ti" },
        { time: 80.26, text: "Te quiero toda sobre mí, ooh" },
        { time: 83.41, text: "" },
        { time: 87.61, text: "Me enamoré, me enamoré" },
        { time: 90.46, text: "Pero está bien, porque estamos enamorados" },
        { time: 93.48, text: "Oh Dios mío, me enamoré" },
        { time: 96.36, text: "Me enamoré del amor" },
        { time: 99.45, text: "Muéstrame amor, yo te doy amor" },
        { time: 102.33, text: "Me enamoré, me enamoré" },
        { time: 105.34, text: "Quiero entrar, por el amor" },
        { time: 108.20, text: "Solo muéstrame amor, solo muéstrame amor" },
        { time: 111.18, text: "La chica está volando, ahora tiene un grupo" },
        { time: 114.14, text: "Tiene un escuadrón, ahora tiene un auto" },
        { time: 117.09, text: "Ella va de club en club, comprando joyas" },
        { time: 119.93, text: "Chica, estás brillando, chica, estás bien, y sí, tú" },
        { time: 123.68, text: "Tan fina como el vino, eres diez como diamantes" },
        { time: 127.21, text: "Te trato como mi último centavo" },
        { time: 129.16, text: "Me voy a la quiebra, no es broma" },
        { time: 131.65, text: "Corto a estas chicas" },
        { time: 133.17, text: "Mato la llamada de rollo" },
        { time: 134.73, text: "Levanto las puertas" },
        { time: 136.16, text: "A ella le gusta mostrar" },
        { time: 137.73, text: "Esas chicas están dormidas" },
        { time: 139.02, text: "Esas chicas se quedaron dormidas" },
        { time: 140.64, text: "Puse un anillo en eso, no tiene anillo" },
        { time: 143.50, text: "De rodillas por ti, mira cómo lo hago, él no lo hizo" },
        { time: 146.50, text: "No puedo hablar por ti, pero sé que él no lo hace" },
        { time: 149.31, text: "Hablo tu idioma" },
        { time: 150.92, text: "Él no te dice cosas, ¿verdad?" },
        { time: 152.44, text: "Como 'Chica, eres peligrosa'" },
        { time: 153.99, text: "Chica, no vi belleza hasta que te vi" },
        { time: 156.58, text: "No hagas trampa como hacen las reinas" },
        { time: 159.57, text: "Sí, sí, sí" },
        { time: 161.55, text: "Déjame cantarte" },
        { time: 162.70, text: "Que esta sea la música del tema" },
        { time: 164.23, text: "Me enamoré, me enamoré" },
        { time: 167.14, text: "Pero está bien, porque estamos enamorados" },
        { time: 170.16, text: "Oh Dios mío, me enamoré" },
        { time: 172.99, text: "Me enamoré del amor" },
        { time: 176.08, text: "Muéstrame amor, yo te doy amor" },
        { time: 179.00, text: "Me enamoré, me enamoré" },
        { time: 181.99, text: "Quiero entrar, por el amor" },
        { time: 184.76, text: "Solo muéstrame amor, solo muéstrame amor" },
        { time: 188.04, text: "Me enamoré, me enamoré" },
        { time: 190.89, text: "Y está bien, porque estoy enamorado" }
    ],
    "You": [
        { time: 15.60, text: "Eres virtuosa más que fiel" },
        { time: 18.08, text: "Algo grandioso, inigualable y un 15 en escala de 1 a 10" },
        { time: 23.06, text: "Tienes el aura y el poder" },
        { time: 25.15, text: "Que conduce al infinito a todo hombre que te suele conocer" },
        { time: 30.45, text: "(Eres mi droga y me causas efecto)" },
        { time: 33.97, text: "Veo arcoíris, estrellitas y el edén" },
        { time: 37.32, text: "(Sueño despierto, soy adicto a tu sexo)" },
        { time: 41.00, text: "Éxtasis divino, medicina del placer" },
        { time: 45.71, text: "Tus labios me saben a miel" },
        { time: 47.14, text: "Y tus fluidos son el néctar que mi lengua saborea cuando hay sed" },
        { time: 51.95, text: "No hay errores en tu ser" },
        { time: 54.40, text: "Y como dios no se equivoca te prefiero 100% en desnudez" },
        { time: 59.45, text: "(Eres vino tinto, mi trago predilecto)" },
        { time: 62.87, text: "Derrámate en mi cuerpo, absórbete en mi piel" },
        { time: 66.40, text: "(Y que esta noche se demore en exceso)" },
        { time: 70.22, text: "Que minutos se hagan horas devorándote mujer" },
        { time: 75.16, text: "(You) Eres afrodisiaco exquisito me excitas sin fin" },
        { time: 82.28, text: "(You) has domado a un salvaje y me entrego a tu aroma sutil" },
        { time: 90.06, text: "(You) has borrado las ansias de aquel hombre infiel y por ti..." },
        { time: 96.82, text: "Soy feliz, yo por ti, pierdo el aliento siento fuego por dentro" },
        { time: 103.73, text: "And baby you, you are my lady" },
        { time: 107.59, text: "It's more than sexual, and you make me complete" },
        { time: 122.52, text: "(Girl)" },
        { time: 130.30, text: "(You need this in your life)" },
        { time: 143.30, text: "(Oye que feeling mami)" },
        { time: 153.69, text: "(The King Stays King)" },
        { time: 170.27, text: "Siempre fui un enigma que nadie pudo entender" },
        { time: 177.45, text: "Navegando entre mujeres a ver quién me pueda complacer" },
        { time: 184.21, text: "Y llegaste tú mi loca amante me haces bien" },
        { time: 193.92, text: "(You) Eres afrodisiaco exquisito me excitas sin fin" },
        { time: 200.63, text: "(You) has domado a un salvaje y me entrego a tu aroma sutil" },
        { time: 208.25, text: "(You) has borrado las ansias de aquel hombre infiel y por ti..." },
        { time: 214.96, text: "Soy feliz, yo por ti, pierdo el aliento siento fuego por dentro" },
        { time: 222.05, text: "And you my baby, my lady" },
        { time: 226.60, text: "And you make me complete" }
      ],
    "Congratulations": [
        { time: 0, text: "¿Dónde estás?" },
        { time: 1.49, text: "Ohhhhh-ohhh (jejeje)" },
        { time: 8.36, text: "Ohhhhh" },
        { time: 12.12, text: "The Divine Feminine, un álbum de Mac Miller" },
        { time: 15.83, text: "Ohhhhh-ohhh" },
        { time: 17.35, text: "(The Divine Feminine, jejeje)" },
        { time: 21.60, text: "(The Divine Feminine, jejeje)" },
        { time: 23.41, text: "Ohhhhh" },
        { time: 26.35, text: "" },
        { time: 29.64, text: "¿Se supone que debo? Ok" },
        { time: 34.61, text: "Amor" },
        { time: 36.54, text: "Amor, amor, amor, amor, amor (sexo)" },
        { time: 40.22, text: "Amor, amor, amor, amor, amor, amor, amor (sexo)" },
        { time: 46.37, text: "Este sol no brilla cuando estoy solo" },
        { time: 50.41, text: "Pierdo la cabeza y pierdo el control" },
        { time: 54.03, text: "Veo tus ojos atravesando mi alma" },
        { time: 57.92, text: "No te sorprendas, esto es todo lo que sé" },
        { time: 61.63, text: "Sentí las alturas y se sintieron como tú" },
        { time: 65.21, text: "Ver un amor como el mío es demasiado bueno para ser verdad" },
        { time: 69.04, text: "Y tú eres demasiado divina para ser solo mía" },
        { time: 72.78, text: "Me recuerdas al color azul" },
        { time: 76.60, text: "Chica, estoy tan enamorado de ti, sí" },
        { time: 81.58, text: "Chica, estoy tan enamorado de ti" },
        { time: 86.28, text: "Sí, sí" },
        { time: 93.65, text: "Sí, sí, sí, sí" },
        { time: 100.09, text: "" },
        { time: 104.04, text: "Bueno, nena" },
        { time: 105.99, text: "Eras todo lo que siempre quise" },
        { time: 107.74, text: "Compré un anillo de boda, está en mi bolsillo" },
        { time: 109.51, text: "Planeaba preguntarte el otro día" },
        { time: 111.09, text: "Sabía que huirías, así que supongo que lo olvidé" },
        { time: 113.35, text: "¿Recuerdas cuando te fuiste a la universidad?" },
        { time: 115.22, text: "Estaba en el teléfono, empezamos a hablar" },
        { time: 117.02, text: "Pasado, presente, futuro, todos los chismes, Dios mío" },
        { time: 120.74, text: "El amor de cachorro no es lo que solía ser, cariño" },
        { time: 122.78, text: "Los sentimientos que tenemos son tan alarmantes" },
        { time: 124.64, text: "Puedo hacerte reír, puedo romper el vidrio" },
        { time: 126.58, text: "Si lo hiciéramos durar, sería una ganga" },
        { time: 128.34, text: "El Sr. Encantador, esa es mi especialidad" },
        { time: 130.25, text: "Estuviste allí antes de los autos lujosos y" },
        { time: 132.19, text: "Estuviste allí cuando yo era solo un artista hambriento" },
        { time: 134.29, text: "Cuando el auto tenía problemas para arrancar" },
        { time: 136.55, text: "Ahora tenemos nuestro propio apartamento, misma caja para el correo" },
        { time: 140.04, text: "La misma canasta para la ropa, la comida en el refrigerador está vieja" },
        { time: 144.12, text: "Y esta mañana cocinaste los huevos con col rizada" },
        { time: 146.73, text: "Intenté hacerlo mientras te vestías" },
        { time: 148.67, text: "Dijiste 'todo lo que piensas es en sexo'" },
        { time: 150.65, text: "Yo como, 'Oh bueno, me conoces tan bien'" },
        { time: 154.35, text: "Y si esto te hace acostarte, juro que no lo diré" },
        { time: 158.20, text: "Y cada vez que llamo a tu teléfono" },
        { time: 160.06, text: "Más vale que contestes tu celular" },
        { time: 161.90, text: "Te juro que me volveré loco" },
        { time: 163.80, text: "Si va directamente al buzón de voz" },
        { time: 165.76, text: "Bueno, soy del tipo celoso" },
        { time: 167.58, text: "Pero juro que esa parte es lo que el cielo es" },
        { time: 169.47, text: "Cuando estoy en esa parte es una vida mejor" },
        { time: 171.22, text: "Esa es la única manera en que trato de terminar la noche" },
        { time: 175.22, text: "Esa es mi única oportunidad, mejor hacerlo bien" },
        { time: 180.87, text: "Tómate tu tiempo, mi amor" },
        { time: 187.76, text: "Porque estoy esperándote, esperándote" },
        { time: 195.64, text: "Y haré que tu mente se vuelva loca" },
        { time: 202.76, text: "Porque estoy esperando aquí para ti, para ti" },
        { time: 211.11, text: "Te acercas conmigo y corres" },
        { time: 215.06, text: "Todo lo que siempre supe fue el color gris" },
        { time: 218.78, text: "Tu hermosura me trae sol" },
        { time: 226.06, text: "Encontré un ángel tan divino" },
        { time: 230.05, text: "El cielo probablemente no es lo mismo sin ti" },
        { time: 234.13, text: "Pero ahora estás en mi mundo" },
        { time: 236.84, text: "En mi mundo, ahhhh-ahh" },
        { time: 244.50, text: "Ahhh-ahhhh, ahhh-ahhh" },
        { time: 250.06, text: "" }
    ]
    ,
    "That's What I Like": [
        { time: 3.57, text: "Tengo un condominio en Manhattan" },
        { time: 5.56, text: "Chica, ¿qué pasa?" },
        { time: 7.67, text: "Tú y tu trasero invitados" },
        { time: 9.41, text: "Así que vamos, empieza a aplaudir" },
        { time: 11.02, text: "Así que muévelo para un pimp" },
        { time: 12.38, text: "Muévelo para mí" },
        { time: 14.24, text: "Da la vuelta y suéltalo para un pimp" },
        { time: 15.68, text: "Suelta, suéltalo para mí" },
        { time: 17.54, text: "Alquilaré una casa en la playa en Miami" },
        { time: 19.46, text: "Despierto sin pijamas" },
        { time: 21.26, text: "Colas de langosta para la cena" },
        { time: 23.38, text: "Julio sirve ese camarón" },
        { time: 25.05, text: "Lo tienes si lo quieres" },
        { time: 26.73, text: "Lo tienes, lo tienes si lo quieres" },
        { time: 28.47, text: "Dijiste que lo tienes si lo quieres" },
        { time: 30.27, text: "Toma mi billetera si la quieres ahora" },
        { time: 32.38, text: "Salta al Cadillac" },
        { time: 33.99, text: "(Chica, pongámosle algunos kilómetros)" },
        { time: 36.05, text: "Lo que sea que quieras" },
        { time: 37.66, text: "(Solo para hacerte sonreír)" },
        { time: 39.83, text: "Te lo mereces, cariño, te lo mereces todo" },
        { time: 42.81, text: "Y te lo voy a dar" },
        { time: 45.49, text: "Chica, brillas tan intensamente" },
        { time: 48.71, text: "Champán de fresa toda la noche" },
        { time: 52.07, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 55.92, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 59.39, text: "Sexo junto al fuego por la noche" },
        { time: 62.82, text: "Sábanas de seda y diamantes blancos" },
        { time: 66.60, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 69.89, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 73.44, text: "Estoy hablando de viajes a Puerto Rico" },
        { time: 75.85, text: "Di la palabra y nos vamos" },
        { time: 78.52, text: "Puedes ser mi chica traviesa" },
        { time: 80.45, text: "Chica, seré un fleeko, mamacita" },
        { time: 83.12, text: "Nunca haré una promesa que no pueda cumplir" },
        { time: 86.11, text: "Prometo que sonreirás y nunca te irás" },
        { time: 89.08, text: "Compras en París" },
        { time: 91.13, text: "Todo en 24 quilates" },
        { time: 93.05, text: "Mira en ese espejo" },
        { time: 94.74, text: "Ahora dime, ¿quién es la más hermosa?" },
        { time: 96.23, text: "¿Eres tú? (¿Eres tú?) ¿Soy yo? (¿Soy yo?)" },
        { time: 99.40, text: "Di que somos nosotros (di que somos nosotros) y estaré de acuerdo, cariño" },
        { time: 103.68, text: "Salta al Cadillac" },
        { time: 104.93, text: "(Chica, pongámosle algunos kilómetros)" },
        { time: 106.73, text: "Lo que sea que quieras" },
        { time: 109.28, text: "(Solo para hacerte sonreír)" },
        { time: 110.89, text: "Te lo mereces, cariño, te lo mereces todo" },
        { time: 114.00, text: "Y te lo voy a dar" },
        { time: 116.73, text: "Chica, brillas tan intensamente" },
        { time: 119.34, text: "Champán de fresa toda la noche" },
        { time: 122.75, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 126.03, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 130.64, text: "Sexo junto al fuego por la noche" },
        { time: 134.18, text: "Sábanas de seda y diamantes blancos" },
        { time: 137.47, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 141.33, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 144.74, text: "Si dices que quieres un buen rato" },
        { time: 148.59, text: "Pues aquí estoy, cariño, aquí estoy" },
        { time: 152.75, text: "Hablame, háblame, háblame" },
        { time: 155.11, text: "Dime lo que tienes en mente" },
        { time: 158.58, text: "Si lo quieres, chica, ven y consíguelo" },
        { time: 163.68, text: "Todo esto está aquí para ti" },
        { time: 167.40, text: "Dime, cariño, dime, dime cariño" },
        { time: 169.89, text: "¿Qué quieres hacer?" },
        { time: 173.27, text: "Chica, brillas tan intensamente" },
        { time: 175.60, text: "Champán de fresa toda la noche" },
        { time: 178.01, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 181.43, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 185.22, text: "Sexo junto al fuego por la noche" },
        { time: 189.00, text: "Sábanas de seda y diamantes blancos" },
        { time: 192.36, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" },
        { time: 196.21, text: "Afortunada tú, eso es lo que me gusta, eso es lo que me gusta" }
      ],
    "Antonia": [
        { time: 11.46, text: "CORO:" },
        
        { time: 24.97, text: "Tu, amor, mi vida" },
        { time: 31.89, text: "estoy amándote" },
        { time: 36.30, text: "tu sol, me alumbra" },
        { time: 42.02, text: "para darte calor" },
      
        { time: 45.71, text: "Este mundo está esperándote" },
        { time: 50.32, text: "en tu sonrisa, mi corazón se llena hoy" },
        { time: 55.69, text: "mi cariño eres la razón" },
        { time: 59.53, text: "de todo lo bendito que hay aquí" },
        { time: 65.65, text: "no habrá fuerza que sea capaz" },
        { time: 69.55, text: "hoy Dios está contigo" },
        { time: 71.78, text: "para siempre, para amarte" },
        { time: 74.00, text: "busco siempre en ti" },
      
        { time: 77.74, text: "CORO" },
      
        { time: 115.19, text: "Ay dulce esperanza" },
        { time: 119.65, text: "te quiero desde siempre" },
        { time: 121.93, text: "ya no puedo estar sin ti, no no no" },
      
        { time: 125.21, text: "Y te doy todo mi amor" },
        { time: 129.82, text: "y quiero todo tu amor" },
        { time: 134.98, text: "Y te doy todo mi amor" },
        { time: 139.83, text: "y quiero todo tu amor" },
        { time: 145.65, text: "Te miro y veo todo" },
        { time: 150.71, text: "con tanta nitidez" },
        { time: 155.86, text: "tu Dios es el de todos" },
        { time: 161.93, text: "¡Dulce Esperanza!" },
      
        { time: 185.11, text: "Y te doy todo mi amor" },
        { time: 190.22, text: "y quiero todo tu amor" },
        { time: 195.23, text: "Y te doy todo tu amor" },
        { time: 201.80, text: "y quiero todo tu amor" }
      ],
    "Te Quiero": [
        { time: 19.40, text: "No, ya no me llores" },
        { time: 25.20, text: "no me vayas a hacer llorar a mí" },
        { time: 32.20, text: "Dame, dame tu mano" },
        { time: 38.40, text: "inténtalo mi niña, quiero verte reír" },
        { time: 45.60, text: "Abrázame fuerte" },
        { time: 48.60, text: "ven corriendo a mí" },
        { time: 51.80, text: "te quiero, te quiero, te quiero" },
        { time: 54.40, text: "y no hago otra cosa que pensar en ti" },
        { time: 64.60, text: "..." },
        { time: 70.60, text: "Tú, tú estás dormida" },
        { time: 76.60, text: "y yo te abrazo, siento que respiras" },
        { time: 83.20, text: "sueño con tu sonrisa" },
        { time: 89.20, text: "te beso muy despacio las mejillas" },
        { time: 95.80, text: "Necesito verte," },
        { time: 100.00, text: "dondequiera que estés" },
        { time: 103.00, text: "te quiero, te quiero, te quiero" },
        { time: 105.60, text: "y no hago otra cosa que pensar en ti" },
        { time: 111.80, text: "sólo vivo y respiro para ti" },
        { time: 118.40, text: "te quiero, te quiero," },
        { time: 128.00, text: "te quiero, te quiero." },
        { time: 138.00, text: "..." },
        { time: 169.20, text: "Abrázame fuerte" },
        { time: 172.40, text: "ven corriendo a mí" },
        { time: 175.40, text: "déjame que te diga otra vez que te quiero" },
        { time: 181.40, text: "te quiero, te quiero," },
        { time: 191.20, text: "te quiero, te quiero," },
        { time: 201.00, text: "te quiero, te quiero." },
        { time: 211.00, text: "..." }
      ]
};

// Función para obtener la letra de una canción
function getLyrics(title) {
    return lyrics[title] || [];
}

// Función para obtener la letra correspondiente al tiempo actual
function getCurrentLyric(title, currentTime) {
    const songLyrics = lyrics[title];
    if (!songLyrics) return '';
    
    for (let i = songLyrics.length - 1; i >= 0; i--) {
        if (currentTime >= songLyrics[i].time) {
            return songLyrics[i].text;
        }
    }
    return '';
}